http:
  port: 3000

db:
  mysql:
    host: 'richole.cn'
    port: 3306
    database: 'blog_dev'
    account: 'root'
    password: 'yudafu'

blog:
  publicRequestUrl: 'http://192.168.10.104:3000/public'